### ISSUE TITLE
ETA request for updated models

### ISSUE THREAD

**Issue by EvanWeiner** [gafr/chainer-fast-neuralstyle-models#4]
Thank you for your hard work on this project. But currently it is not usable due to the changes on the recent version. As you wrote "change on how the models are trained which makes them not suitable for the most recent version relased. Will update here soon." -- this issue is a request for an estimated time. Thanks again!

**Comment by 6o6o** [comment]
Thanks for your interest. Since no models were added after the initial repo creation, this remark still applies to all of them. The latest compatible commit is https://github.com/yusuketomoto/chainer-fast-neuralstyle/tree/0d96350

The project is open for anyone to contribute either via PR, or directly contacting me or @garf. As soon as we receive some new models, we'll update the description.
